version: '3'
services:
  clip_sharing_rails:
    container_name: clip_sharing_rails
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle_path:/bundle
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    links:
      - clip_sharing_postgres:clip_sharing_postgres
    depends_on:
      - clip_sharing_postgres
    tty: true
    stdin_open: true

  clip_sharing_postgres:
    container_name: clip_sharing_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  bundle_path:
  postgres_data:
